---
title: "mbdmbd_viewer"
author: "Liam R Mitchell"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("reticulate")
library("tidyverse")
library("ggpubr")
library("lubridate")
library("mclust")
library("uwot")
```

# env setup
## associate all the packages with Renv
```{r renvInit, eval=FALSE}
### RUN THIS WHEN YOU NEED TO CREATE/RECREATE PY ENV
renv::init()
```

```{r renvPyConnection}
# this PATH is the executable python from inside that
pyPath <- "/home/liam/miniconda3/envs/mbdmbd/bin/python"
renv::use_python(
    name = pyPath, 
    type = "conda")
```

```{python}
import imp
import xpore_readnames
imp.reload(xpore_readnames)
import mbdmbd
imp.reload(mbdmbd)

######## args for everything #########
xpath="/work/liam/nfruns/ADARknockdowncomparison/onB2/xpipor-pipe-pore/output/comparisons/mouse-antiadar-scramble/majority_direction_kmer_diffmod.table"
adir="/work/liam/nfruns/ADARknockdowncomparison/onB2/xpipor-pipe-pore/output/mouse_antiadar"
bdir="/work/liam/nfruns/ADARknockdowncomparison/onB2/xpipor-pipe-pore/output/mouse_scramble"
# compile args
arg_xporern = ["xpore_readnames.py","--xpore_table",xpath,"--sampleA_dir",adir,"--sampleB_dir",bdir]

### unmodified sample
bamdirA="/storage/common/rebasecall/p48_anti-adar_guppy6.4"
fdirA="/data/nanopore/data/p48-51_20210210_Adar-Abeta-Aza_R1_SQK_RNA002_HT22/P48_Anti-adar/20210210_2130_1-A1-D1_PAE86248_66c1fc9e/"
## modified sample
bamdirB="/storage/common/rebasecall/p50_Scramble_Si_guppy6.4"
fdirB="/data/nanopore/data/p48-51_20210210_Adar-Abeta-Aza_R1_SQK_RNA002_HT22/P50_Scramble-Si/20210210_2130_1-E9-H9_PAE86613_180257c4/"
# compile args
arg_kmertab_unmod = ['mbdmbd.py','--bamdir',bamdirA,'--fdir',fdirA]
arg_kmertab_mod = ['mbdmbd.py','--bamdir',bamdirB,'--fdir',fdirB]

########### run #############
xporereadnames = xpore_readnames.get_xpore_readnames(arg_xporern)
kmer_table_mod = mbdmbd.get_kmer_table_coord(xporereadnames, arg_kmertab_mod)
kmer_table_unmod = mbdmbd.get_kmer_table_coord(xporereadnames, arg_kmertab_unmod)
```

```{r pyRhandoff}
kmer_table <- rbind(
  reticulate::py$kmer_table_mod %>% 
    mutate(origin="mod"),
  reticulate::py$kmer_table_unmod %>% 
    mutate(origin="unmod")
) %>% 
  # this filter is because AAAAA is a kmer which cannot be unambiguously determined to match sig vs seq
  filter(kmer != "AAAAA")
```

```{r clustering}
kmerClustData <- list()
for(KMER in unique(kmer_table$kmer)) {
  clusterdata <- kmer_table %>% 
    filter(kmer == KMER)
  # extract raw signal
  signal_matrix <- as.data.frame(lapply(cbind(transpose(clusterdata$signal)), unlist), col.names = 1:50) 
  #%>% select(X31:X40)
  
  # get BIC clustering
  mickey_ds <- Mclust(signal_matrix)

  kmerClustData[[KMER]] <- mickey_ds
  break
}

plot(umap(signal_matrix))

# plots to visualize the goddamn currents
plotdata <- signal_matrix %>% 
  mutate(origin = clusterdata$origin,
         clusterID = as.factor(mickey_ds$classification)) %>% 
  # normalize for read diff between samp
  group_by(origin) %>% 
  mutate(sampleSum = n()) %>% 
  group_by(clusterID, origin) %>% 
  summarise(normCount = n()/sampleSum) %>% 
  distinct()

p <- ggplot(plotdata, aes(x = origin, y = normCount, fill = clusterID)) +
  geom_col(position = "dodge")

plot(p)
```

```{r}
# stupid idea, what if I correlate origin with clust ID?
test <- kmer_table %>% filter(kmer == i)
test$cluster_id <- as.factor(mclust$classification)

plotdata <- test %>% 
  group_by(cluster_id, origin) %>% 
  count() %>% 
  group_by(origin) %>% 
  mutate(all_clust_total = sum(n)) %>% 
  ungroup() %>% 
  mutate(norm_count = n / all_clust_total)

p <- ggplot(plotdata, aes(x = origin, y = norm_count , fill = origin)) + 
  geom_col() + 
  facet_grid(cols = vars(cluster_id))

plot(p)
```

```{r}

```

